name = "GeodesicLM"
uuid = "ef14dfaf-8eb7-4021-bbb1-710ada96a62d"
authors = ["Gabriel Kronberger"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.13"
LinearAlgebra = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
